# Generated by Django 5.1.5 on 2025-01-30 17:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del área.', max_length=100, unique=True, verbose_name='Nombre del área')),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Ingrese la capacidad máxima para esta área.', verbose_name='Capacidad máxima')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre completo del voluntario.', max_length=100, verbose_name='Nombre completo')),
                ('identificacion', models.CharField(help_text='Ingrese la identificación del voluntario.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Solo letras y números.', regex='^[A-Za-z0-9]+$')], verbose_name='Identificación')),
                ('email', models.EmailField(help_text='Ingrese el correo electrónico del voluntario.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')], verbose_name='Correo electrónico')),
                ('tipo', models.CharField(choices=[('Regular', 'Regular'), ('Especial', 'Especial')], default='Regular', help_text='Seleccione el tipo de voluntario.', max_length=10, verbose_name='Tipo de voluntario')),
                ('qr_code', models.ImageField(blank=True, help_text='Código QR generado automáticamente.', upload_to='qr_codes/', verbose_name='Código QR')),
                ('area', models.ForeignKey(blank=True, help_text='Seleccione el área asignada al voluntario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.area', verbose_name='Área asignada')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se realizó la asignación.', verbose_name='Fecha de asignación')),
                ('entrada', models.TimeField(blank=True, help_text='Hora en que el voluntario registró su entrada.', null=True, verbose_name='Hora de entrada')),
                ('salida', models.TimeField(blank=True, help_text='Hora en que el voluntario registró su salida.', null=True, verbose_name='Hora de salida')),
                ('area', models.ForeignKey(help_text='Área donde está asignado el voluntario.', on_delete=django.db.models.deletion.CASCADE, to='asistencia.area', verbose_name='Área asignada')),
                ('voluntario', models.ForeignKey(help_text='Seleccione el voluntario.', on_delete=django.db.models.deletion.CASCADE, to='asistencia.voluntario', verbose_name='Voluntario')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha', 'entrada'],
                'constraints': [models.UniqueConstraint(fields=('voluntario', 'fecha'), name='unique_asignacion_voluntario_fecha')],
            },
        ),
    ]
